### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/plpgsql_check#21] opened 2016-08-26 15:52 UTC
Hi,

I see that you released 1.0.5 yesterday, but that was released on July. That will cause issues with existing packages (as I already pushed 1.0.5 to repos last month or so). Can you please fix this? I think it would be 1.0.6.

Regards, Devrim

**Comment by okbob** [comment] 2016-08-26 16:00
2016-08-26 17:52 GMT+02:00 Devrim Gündüz <notifications@github.com>:

> Hi,
>
> I see that you released 1.0.5 yesterday, but that was released on July.
> That will cause issues with existing packages (as I already pushed 1.0.5 to
> repos last month or so). Can you please fix this? I think it would be 1.0.6.
>
> Regards, Devrim
>

the issue is the tag related to different commit or just reused tag?

This repeated issue is my mistake :( - there was not any significant change
- there was just issue in META for PGXN

Pavel

**Comment by devrimgunduz** [comment] 2016-08-26 16:26
Hi,

Still, the tarball provided by SRPMs no longer match with the one that is published in website. This is not looking good :/

Any chance that you can release 1.0.6?

Regards, Devrim

**Comment by okbob** [comment] 2016-08-26 16:45
2016-08-26 18:26 GMT+02:00 Devrim Gündüz <notifications@github.com>:

> Hi,
>
> Still, the tarball provided by SRPMs no longer match with the one that is
> published in website. This is not looking good :/
>
> Any chance that you can release 1.0.6?
>
It is not a problem. I'll do it today.

Regards

Pavel

**Comment by okbob** [comment] 2016-08-26 17:40
Should be fixed now, please check it

https://github.com/okbob/plpgsql_check/releases/tag/v1.0.6

Regards

Pavel

2016-08-26 18:44 GMT+02:00 Pavel Stehule <pavel.stehule@gmail.com>:

**Closed** 2016-09-17 11:12 UTC
